/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab;

import javax.swing.ImageIcon;

/**
 *
 * @author Pavilion 14-N036
 */
public class NewJFrame extends javax.swing.JFrame {
    
    int int_vidaQ = 1900;
    int int_vidaD = 2000;
    int int_vidaR = 2200;
    int int_vidaDS = 2300;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        VidaQ = new javax.swing.JProgressBar();
        Attackd = new javax.swing.JButton();
        Attacks = new javax.swing.JButton();
        Heal = new javax.swing.JButton();
        VidaR = new javax.swing.JProgressBar();
        AttackD = new javax.swing.JButton();
        AttackS = new javax.swing.JButton();
        Heal2 = new javax.swing.JButton();
        VidaD = new javax.swing.JProgressBar();
        AttackQ = new javax.swing.JButton();
        AttackR = new javax.swing.JButton();
        Heal3 = new javax.swing.JButton();
        VidaDS = new javax.swing.JProgressBar();
        Attackq = new javax.swing.JButton();
        Attackr = new javax.swing.JButton();
        Heal4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1080, 720));
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/leon.png"))); // NOI18N
        jLabel1.setText("QUIMERA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 480, 319);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unicornio.png"))); // NOI18N
        jLabel2.setText("RAINBOW KILLER");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 290, 489, 369);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hunter.png"))); // NOI18N
        jLabel3.setText("DRAGUL");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(860, 0, 450, 284);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caballero.png"))); // NOI18N
        jLabel4.setText("DARK");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(860, 280, 470, 382);

        VidaQ.setMaximum(1900);
        VidaQ.setValue(1900);
        getContentPane().add(VidaQ);
        VidaQ.setBounds(470, 40, 158, 34);

        Attackd.setText("Attack Dragul");
        Attackd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttackdActionPerformed(evt);
            }
        });
        getContentPane().add(Attackd);
        Attackd.setBounds(500, 100, 100, 23);

        Attacks.setText("Attack Dark");
        Attacks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttacksActionPerformed(evt);
            }
        });
        getContentPane().add(Attacks);
        Attacks.setBounds(500, 150, 100, 23);

        Heal.setText("Heal");
        Heal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HealActionPerformed(evt);
            }
        });
        getContentPane().add(Heal);
        Heal.setBounds(500, 200, 100, 23);

        VidaR.setMaximum(2200);
        VidaR.setValue(2200);
        getContentPane().add(VidaR);
        VidaR.setBounds(520, 380, 146, 35);

        AttackD.setText("Attack Dragul");
        AttackD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttackDActionPerformed(evt);
            }
        });
        getContentPane().add(AttackD);
        AttackD.setBounds(540, 460, 100, 23);

        AttackS.setText("Attack Dark");
        AttackS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttackSActionPerformed(evt);
            }
        });
        getContentPane().add(AttackS);
        AttackS.setBounds(540, 530, 100, 23);

        Heal2.setText("Heal");
        Heal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Heal2ActionPerformed(evt);
            }
        });
        getContentPane().add(Heal2);
        Heal2.setBounds(540, 590, 100, 23);

        VidaD.setMaximum(2000);
        VidaD.setValue(2000);
        getContentPane().add(VidaD);
        VidaD.setBounds(810, 40, 146, 34);

        AttackQ.setText("Attack Quimera");
        AttackQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttackQActionPerformed(evt);
            }
        });
        getContentPane().add(AttackQ);
        AttackQ.setBounds(820, 100, 120, 23);

        AttackR.setText("Attack Rainbow");
        AttackR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttackRActionPerformed(evt);
            }
        });
        getContentPane().add(AttackR);
        AttackR.setBounds(820, 150, 120, 20);

        Heal3.setText("Heal");
        Heal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Heal3ActionPerformed(evt);
            }
        });
        getContentPane().add(Heal3);
        Heal3.setBounds(830, 200, 100, 23);

        VidaDS.setMaximum(2300);
        VidaDS.setValue(2300);
        getContentPane().add(VidaDS);
        VidaDS.setBounds(810, 380, 146, 35);

        Attackq.setText("Attack Quimera");
        Attackq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttackqActionPerformed(evt);
            }
        });
        getContentPane().add(Attackq);
        Attackq.setBounds(820, 450, 130, 23);

        Attackr.setText("Attack Rainbow");
        Attackr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttackrActionPerformed(evt);
            }
        });
        getContentPane().add(Attackr);
        Attackr.setBounds(820, 510, 130, 23);

        Heal4.setText("Heal");
        Heal4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Heal4ActionPerformed(evt);
            }
        });
        getContentPane().add(Heal4);
        Heal4.setBounds(830, 580, 110, 23);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arena06.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, -140, 1560, 1050);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(680, 280, 146, 96);

        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(1040, 130, 34, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AttacksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttacksActionPerformed
        // TODO add your handling code here:
        VidaDS.setValue(int_vidaDS);
        int_vidaDS -=90 + (Math.random()*1000)%5;
    }//GEN-LAST:event_AttacksActionPerformed

    private void AttackDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttackDActionPerformed
        // TODO add your handling code here:
        VidaD.setValue(int_vidaD);
        int_vidaD -=80 + (Math.random()*1000)%5;
    }//GEN-LAST:event_AttackDActionPerformed

    private void AttackrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttackrActionPerformed
        // TODO add your handling code here:
        VidaR.setValue(int_vidaR);
        int_vidaR -=90 + (Math.random()*1000)%5;
    }//GEN-LAST:event_AttackrActionPerformed

    private void AttackdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttackdActionPerformed
        // TODO add your handling code here:
        VidaD.setValue(int_vidaD);
        int_vidaD -=90 + (Math.random()*1000)%5;
    }//GEN-LAST:event_AttackdActionPerformed

    private void AttackSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttackSActionPerformed
        // TODO add your handling code here:
        VidaDS.setValue(int_vidaDS);
        int_vidaDS -=80 + (Math.random()*1000)%5;
    }//GEN-LAST:event_AttackSActionPerformed

    private void AttackQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttackQActionPerformed
        // TODO add your handling code here:
        VidaQ.setValue(int_vidaQ);
        int_vidaQ -=80 + (Math.random()*1000)%5;
    }//GEN-LAST:event_AttackQActionPerformed

    private void AttackRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttackRActionPerformed
        // TODO add your handling code here:
        VidaR.setValue(int_vidaR);
        int_vidaR -=90 + (Math.random()*1000)%5;
    }//GEN-LAST:event_AttackRActionPerformed

    private void AttackqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttackqActionPerformed
        // TODO add your handling code here:
        VidaQ.setValue(int_vidaQ);
        int_vidaQ -=100 + (Math.random()*1000)%5;
    }//GEN-LAST:event_AttackqActionPerformed

    private void Heal4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Heal4ActionPerformed
        // TODO add your handling code here:
        VidaDS.setValue(int_vidaDS);
        int_vidaDS +=60;
    }//GEN-LAST:event_Heal4ActionPerformed

    private void Heal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Heal3ActionPerformed
        // TODO add your handling code here:
        VidaD.setValue(int_vidaD);
        int_vidaD +=50;
    }//GEN-LAST:event_Heal3ActionPerformed

    private void Heal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Heal2ActionPerformed
        // TODO add your handling code here:
        VidaR.setValue(int_vidaR);
        int_vidaR +=55;
    }//GEN-LAST:event_Heal2ActionPerformed

    private void HealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HealActionPerformed
        // TODO add your handling code here:
        VidaQ.setValue(int_vidaQ);
        int_vidaQ +=60;
    }//GEN-LAST:event_HealActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AttackD;
    private javax.swing.JButton AttackQ;
    private javax.swing.JButton AttackR;
    private javax.swing.JButton AttackS;
    private javax.swing.JButton Attackd;
    private javax.swing.JButton Attackq;
    private javax.swing.JButton Attackr;
    private javax.swing.JButton Attacks;
    private javax.swing.JButton Heal;
    private javax.swing.JButton Heal2;
    private javax.swing.JButton Heal3;
    private javax.swing.JButton Heal4;
    private javax.swing.JProgressBar VidaD;
    private javax.swing.JProgressBar VidaDS;
    private javax.swing.JProgressBar VidaQ;
    private javax.swing.JProgressBar VidaR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
